language: go

go:
  - 1.4
  - tip

env:
  - GOARCH=amd64

notifications:
  email: false

script:
    - go test  -coverprofile=coverage.txt -covermode=atomic github.com/resal81/molkit/blocks
    - go test  -coverprofile=coverage.txt -covermode=atomic github.com/resal81/molkit/molio/chm

after_success:
      - bash <(curl -s https://codecov.io/bash)
